configuration: Release

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore

# package Web Application project for Web Deploy
build:
  project: fantasy-surf\back-end\fantasy-surf\Fantasy-Surf.sln
  verbosity: minimal
  publish_wap: true
